#ifndef PIXTOOLS_PIXLETTERS_H
#define PIXTOOLS_PIXLETTERS_H

#define PIX_LETTER_SIZE_HEIGHT 8

extern char PIX_LETTER_EMPTY[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_A[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_B[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_C[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_D[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_E[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_F[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_G[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_H[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_I[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_J[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_K[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_L[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_M[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_N[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_O[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_P[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_Q[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_R[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_S[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_T[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_U[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_V[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_W[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_X[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_Y[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_Z[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_0[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_1[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_2[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_3[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_4[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_5[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_6[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_7[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_8[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_9[PIX_LETTER_SIZE_HEIGHT];
extern char PIX_LETTER_SLASH[PIX_LETTER_SIZE_HEIGHT];

char *mappingCharToPixelLetter(char c);

#endif // PIXTOOLS_PIXLETTERS_H
