#ifndef JOYSTICK_RG35XXH_BUTTON_ENUM_H
#define JOYSTICK_RG35XXH_BUTTON_ENUM_H

typedef enum
{
    JOYSTICK_RG35XXH_VOLUME_DOWN  = 1,
    JOYSTICK_RG35XXH_VOLUME_UP    = 2,
    JOYSTICK_RG35XXH_A            = 3,
    JOYSTICK_RG35XXH_B            = 4,
    JOYSTICK_RG35XXH_Y            = 5,
    JOYSTICK_RG35XXH_X            = 6,
    JOYSTICK_RG35XXH_L1           = 7,
    JOYSTICK_RG35XXH_R1           = 8,
    JOYSTICK_RG35XXH_SELECT       = 9,
    JOYSTICK_RG35XXH_START        = 10,
    JOYSTICK_RG35XXH_FUNCTION     = 11,
    JOYSTICK_RG35XXH_L3           = 12,
    JOYSTICK_RG35XXH_L2           = 13,
    JOYSTICK_RG35XXH_R2           = 14,
    JOYSTICK_RG35XXH_R3           = 15,
    JOYSTICK_RG35XXH_FONCTION_BIS = 16
} JoystickRG35XXHButton;

#endif // JOYSTICK_RG35XXH_BUTTON_ENUM_H
