#ifndef JOYSTICK_RG35XXH_HAT_ENUM_H
#define JOYSTICK_RG35XXH_HAT_ENUM_H

#include <SDL.h>

typedef enum
{
    JOYSTICK_RG35XXH_HAT_UP    = SDL_HAT_UP,
    JOYSTICK_RG35XXH_HAT_DOWN  = SDL_HAT_DOWN,
    JOYSTICK_RG35XXH_HAT_LEFT  = SDL_HAT_LEFT,
    JOYSTICK_RG35XXH_HAT_RIGHT = SDL_HAT_RIGHT
} JoystickRG35XXHHat;

#endif // JOYSTICK_RG35XXH_HAT_ENUM_H
