#ifndef JOYSTICK_RG35XXH_AXIS_ENUM_H
#define JOYSTICK_RG35XXH_AXIS_ENUM_H

// SDL_JOYAXISMOTION: e.jaxis.axis index for RG35XXH analog sticks.
// e.jaxis.value range: -32768 .. 32767. Apply JOYSTICK_RG35XXH_AXIS_DEADZONE.
typedef enum
{
    JOYSTICK_RG35XXH_AXIS_LEFT_X  = 0,
    JOYSTICK_RG35XXH_AXIS_LEFT_Y  = 1,
    JOYSTICK_RG35XXH_AXIS_RIGHT_X = 2,
    JOYSTICK_RG35XXH_AXIS_RIGHT_Y = 3
} JoystickRG35XXHAxis;

#define JOYSTICK_RG35XXH_AXIS_DEADZONE 8000

#endif // JOYSTICK_RG35XXH_AXIS_ENUM_H
